pygments: true
download:
    version: 0.6.1
    date: "September 27, 2011"
    size: 18kb gzipped
    blurb: Second alpha release of batman.js. Please see the blog post or release notes for more information.
examples:
    - title: Hello World
      key: hello world
    - title: Alfred - Batman's Todos
      key: alfred
