pygments: true
download:
    version: 0.14.0
    date: "February 14th, 2013"
    size: 40kb minified and gzipped
    blurb: "Massive stability update: performance and bugfixes."
examples:
    - title: Hello World
      url: '/hello_world.html'
      key: hello world
    - title: Alfred - Batman's Todos
      url: '/alfred.html'
      key: alfred
    - title: Shopify Classifieds
      url: 'http://batman-classifieds.heroku.com/'
      key: classifieds
