pygments: true
download:
    version: 0.8.0
    date: "November 22nd, 2011"
    size: 18kb gzipped
    blurb: Fourth alpha release of batman.js. Please see the blog post or release notes for more information.
examples:
    - title: Hello World
      url: '/hello_world.html'
    - title: Alfred - Batman's Todos
      url: '/alfred.html'
    - title: Shopify Classifieds
      url: 'http://batman-classifieds.heroku.com/'
